name: dox
description: This is a cli tool to generate migration, model and to handle database migration with dox framework. It support up and down methods to control migration version.
version: 2.0.0
repository: https://github.com/dartondox/dox
homepage: https://dartondox.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dox_migration: ^2.0.0
  watcher: ^1.0.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dox: dox
