name: dox_framework

packages:
  - packages/**

scripts:

  test:
    exec: dart test --concurrency=1
    packageFilters:
      ignore: "dox_query_builder"

  test_query_builder_postgres:
    exec: DRIVER=postgres dart test --concurrency=1
    packageFilters:
      noSelect: true
      scope: "dox_query_builder"

  test_query_builder_mysql:
    exec: DRIVER=mysql dart test --concurrency=1
    packageFilters:
      noSelect: true
      scope: "dox_query_builder"