name: dox_core
description: Dox core
version: 0.0.2
repository: https://github.com/necessarylion/dox-core

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  postgres: ^2.6.1
  dart_dotenv: ^1.0.1
  dox_query_builder: ^1.0.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
