name: dox_core
description: A perfect solution for your web backend development with dart that offers a wide range of features to help you build powerful and scalable web applications.
version: 2.0.0-alpha.0
repository: https://github.com/dartondox/dox-core

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  encrypt: ^5.0.1
  bcrypt: ^1.1.3
  path: ^1.8.3
  sprintf: ^7.0.0
  mime: ^1.0.4
  string_scanner: ^1.1.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  http: ^0.13.6
  redis: ^3.1.0
  postgres_pool: ^2.1.6
  dox_query_builder: ^1.1.13
  dox_migration: ^1.0.4
  http_parser: ^4.0.2
