name: dox_core
description: Dox core
version: 1.0.0-alpha.0
repository: https://github.com/dartondox/dox-core

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  encrypt: ^5.0.1
  bcrypt: ^1.1.3
  dart_dotenv: ^1.0.1
  path: ^1.8.3
  sprintf: ^7.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  http: ^0.13.6
