name: dox_core
description: Dox core
version: 0.0.16
repository: https://github.com/necessarylion/dox-core

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  postgres_pool: ^2.1.6
  encrypt: ^5.0.1
  bcrypt: ^1.1.3
  dart_dotenv: ^1.0.1
  dox_query_builder: ^1.1.6
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
