name: dox_app
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  postgres: ^3.0.5
  ioredis: ^1.0.2
  short_uuids: ^2.0.0
  dox_auth: ^2.0.0
  dox_migration: ^2.0.0
  dox_core: ^2.0.0
  dox_websocket: ^1.0.0
  dox_query_builder: ^2.0.0

dev_dependencies:
  dox_builder: ^2.0.0
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.0.0

assets:
  - .env