name: dox_builder
description: Dox builder for dox framework
version: 1.0.4
repository: https://github.com/dartondox/dox
homepage: https://dartondox.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.0
  source_gen: ^1.3.1
  analyzer: ^5.12.0
  dox_annotation: ^1.0.5-alpha1.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
