name: dox_annotation
description: Dox annotation for dox framework
version: 1.0.5-alpha2.0
repository: https://github.com/dartondox/dox
homepage: https://dartondox.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
