import 'dart:convert';
import 'dart:io';

import 'package:dox_core/dox_core.dart';
import 'package:dox_core/websocket/socket_storage.dart';
import 'package:uuid/uuid.dart';

Uuid uuid = Uuid();

class DoxWebsocket {
  /// initially default room is path of the socket eg. /ws
  final String _defaultRoom;

  /// storage to store active socket connection
  final SocketStorage _storage = SocketStorage();

  DoxWebsocket(this._defaultRoom);

  /// registered websocket events listener
  final Map<String, Function> _events = <String, Function>{};

  /// register websocket event
  /// ```
  /// DoxWebsocket.on('info', (SocketEmitter emitter, message) {
  ///   /// your logic here
  /// });
  /// ```
  void on(String event, Function(SocketEmitter, dynamic) controller) {
    _events[event] = controller;
  }

  /// handle http request and convert into websocket
  Future<WebSocket?> handle(DoxRequest req) async {
    WebSocket ws = await WebSocketTransformer.upgrade(req.httpRequest);

    /// create socket id for each client connection
    /// socketId is just `uuid` generated by us
    String socketId = _createSocketId();

    /// add to active ws connection storage to reuse later
    _storage.addWebSocketInfo(socketId, ws);

    /// add socket id to the room default room is the route eg. /ws
    _storage.addWebSocketIdToRoom(socketId, _defaultRoom);

    /// listen for new message sent from client
    ws.listen(
      (dynamic data) async {
        /// decode message to map
        Map<String, dynamic> payload = jsonDecode(data);

        String eventName = payload[WEB_SOCKET_EVENT_KEY];
        dynamic message = payload[WEB_SOCKET_MESSAGE_KEY];

        /// get controller fom event controller
        /// eg. socket.on(eventName, controller);
        Function? controller = _events[eventName];

        if (controller != null) {
          /// prepare emitter to pass to controller
          SocketEmitter emitter =
              SocketEmitter(sender: socketId, roomId: _defaultRoom);
          Function.apply(controller, <dynamic>[emitter, message]);
        }

        /// if event name is WEB_SOCKET_JOIN_ROOM_EVENT_NAME,
        /// join to the room and message is room name
        if (eventName == WEB_SOCKET_JOIN_ROOM_EVENT_NAME) {
          String room = message;
          _storage.addWebSocketIdToRoom(socketId, room);
        }
      },
      onDone: () {
        /// once websocket is disconnected, remove socket from
        /// active connection storage
        _storage.removeWebSocketInfo(socketId);
      },

      /// coverage:ignore-start
      onError: (dynamic error) {
        /// if websocket has error, remove socket from
        /// active connection storage
        _storage.removeWebSocketInfo(socketId);
      },

      /// coverage:ignore-end
    );

    /// return websocket, so that response controller
    /// do not close the connection
    return ws;
  }

  /// creating socket id with unique timestamp
  String _createSocketId() {
    return 'ws:${uuid.v4()}';
  }
}
