name: dox_query_builder
description: PostgresSQL, MYSQL query builder, Support Model, Where, orWhere, Find, Join, softDeletes, Debugging and many mores.
version: 2.1.0
repository: https://github.com/dartondox/dox
homepage: https://dartondox.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  postgres: ^3.0.5
  mysql1: ^0.20.0
  dox_annotation: ^1.0.5
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  dox_builder: ^2.0.0
