name: dox_auth
description: Authentication package for dox framework with jsonwebtoken(jwt) driver.
version: 2.0.0
repository: https://github.com/dartondox/dox

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.8.2
  dox_annotation: ^1.0.5
  dox_query_builder: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
