name: dox_migration
description: Database migration package for Postgres SQL
version: 2.0.0-alpha.1
repository: https://github.com/dartondox/dox

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  postgres_pool: ^2.1.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dox_migration: dox_migration
