name: dox_websocket
description: Websocket library for dox framework.
version: 1.0.0-beta.1
repository: https://github.com/dartondox/dox
environment:
  sdk: ^3.1.0

dependencies:
  uuid: ^3.0.6
  dox_annotation: ^1.0.5-alpha1.9
  ioredis: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
