name: MkDocs Deploy

on:
  push:
    # branches:
    #   - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Get GitHub repository URL
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          echo "Repository URL: $REPO_URL"

      - name: Deploy to GitHub Pages with Force Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global init.defaultBranch main
          cd site
          git init
          git checkout -b gh-pages
          git remote add origin https://github.com/dartondox/dox.git
          git add .
          git commit -m "Deploy MkDocs to GitHub Pages"
      - name: Push
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          tags: false
          branch: gh-pages
          force: true
