name: Publish docs via GitHub Pages
on:
  push:
    # branches:
    #   - main

jobs:
  publish:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          PERSONAL_TOKEN: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
