name: MkDocs Deploy

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    if: |
      startsWith(github.event.head_commit.message, 'update:docs')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global init.defaultBranch main

      - name: Deploy to GitHub Pages with Force Push
        run: |
          cd site
          git init
          git remote add origin https://github-actions[bot]:${{ secrets.PUSH_TO_PROTECTED_BRANCH }}@github.com/dartondox/dox.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy MkDocs to GitHub Pages"
          git push --set-upstream origin gh-pages -f
